Hype Video:

[3s] Helmet shot
[2s] Starting Bike
[3s] 3-4 Driving Bike Clips
[3s] Arriving at House
[15s] House Events/Dye
[3-4s] Panning to Pier Events
[?] Basketball, Gym, Lake, Mountain weekend shots
[?] Drone footage of band


